name: SignStonks
version: ${project.version}
main: com.nchroniaris.signstonks.SignStonks
api-version: 1.14
depend: [ SignShop, NBTAPI ]
description: Uses SignShop and an external data source to enable a "stock market" in game
